### ISSUE TITLE
Add usage to readme?

### ISSUE THREAD

**Issue by ChillarAnand** [erm/fikki#1]
A brief usage description will be useful to get started quickly.

**Comment by erm** [comment]
@ChillarAnand It is currently a very heavy work in progress, so I won't be including any general usage notes until it is closer to a releasable state. I don't imagine it will be production-ready for awhile (at the very least until Python 3.7 is released), and it will not support Python versions below 3.7.

If you'd like to try it out for development/non-production usage, you will need to install the latest beta release of [Python 3.7](https://www.python.org/downloads/release/python-370b5/). I'll see about splitting the classes into separate files this weekend and adding some development/usage instructions.

**Comment by ChillarAnand** [comment]
Sure, thanks.

**Comment by erm** [comment]
@ChillarAnand I've added some development usage instructions to the README (be warned, things may drastically change at this point). I will add more general usage instructions at a later time - I will leave this issue open until then.

**Comment by ChillarAnand** [comment]
Sure. Thanks.
